language: node_js

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - node

script:
  - npm run test:prod

after_success:
  - npm run report-coverage
